-- Money Harvester Pro tables.
-- Run this in the target Supabase SQL editor before connecting a live account.
create table if not exists profiles (
  id text primary key,
  metaapi_account_id text not null unique,
  broker_name text,
  server text,
  login text,
  account_type text,
  connection_state text not null default 'DISCONNECTED',
  leverage integer,
  balance numeric,
  equity numeric,
  updated_at timestamptz not null default now()
);

create table if not exists states (
  id uuid primary key default gen_random_uuid(),
  account_id text not null references profiles(id) on delete cascade,
  symbol text not null,
  current_state text not null default 'SCANNING',
  liquidity_pool jsonb not null default '[]'::jsonb, 
  poi jsonb,
  diagnostics_log text[] not null default '{}',
  htf_bias text,
  htf_conflict boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (account_id, symbol)
);

create table if not exists journal (
  id uuid primary key default gen_random_uuid(),
  account_id text not null references profiles(id) on delete cascade,
  symbol text not null,
  real_symbol text,
  direction text not null,
  entry numeric,
  sl numeric,
  initial_sl numeric,
  tp numeric,
  lot numeric,
  pnl numeric,
  r_multiple numeric,
  status text not null default 'OPEN',
  broker_position_id text,
  broker_order_id text,
  broker_status text,
  broker_updated_at timestamptz,
  poi_type text,
  bos_mss_tag text,
  htf_bias text,
  spread numeric,
  slippage numeric,
  chart_snapshot_url text,
  leverage integer,
  margin_used numeric,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

-- Keep existing installations compatible when the journal table already exists.
alter table journal add column if not exists initial_sl numeric;
alter table journal add column if not exists broker_position_id text;
alter table journal add column if not exists broker_order_id text;
alter table journal add column if not exists broker_status text;
alter table journal add column if not exists broker_updated_at timestamptz;

create table if not exists risk_settings (
  account_id text primary key references profiles(id) on delete cascade,
  risk_per_trade numeric not null default 1,
  daily_loss numeric not null default 3,
  weekly_loss numeric not null default 6,
  spread_multiplier numeric not null default 2.5,
  news_minutes integer not null default 30
);

create table if not exists equity_history (
  id bigint generated by default as identity primary key,
  account_id text not null references profiles(id) on delete cascade,
  timestamp timestamptz not null default now(),
  balance numeric not null,
  equity numeric not null
);

create index if not exists states_account_symbol_idx on states(account_id, symbol);
create index if not exists journal_account_created_idx on journal(account_id, created_at desc);
create index if not exists equity_history_account_time_idx on equity_history(account_id, timestamp asc);

alter table profiles enable row level security;
alter table states enable row level security;
alter table journal enable row level security;
alter table risk_settings enable row level security;
alter table equity_history enable row level security;